### PR TITLE
Add and use Spotify.Auth struct to decouple from Plug.Conn

### LINKED ISSUE #4: Can't use without cookies?
It looks like any function that makes a request to Spotify needs a Plug.Conn with a cookie inside that contains the auth tokens. This effectively limits this library to be used only in conjunction with a web application.

What about providing some way to store the auth data in a process instead so that one could use this library without a browser involved?

### PR DESCRIPTION
**Pull request by adamzaninovich**
Closes #4 

These changes do not alter the existing public API of the library; they simply add the option to use an included `Spotify.Auth` struct to hold auth tokens instead of having to relying on `Plug.Conn` to store the tokens in cookies.

This brings about some internal changes and refactors that I believe lower the complexity of the library slightly by decoupling some parts of the internals from `Plug.Conn`. Of course, in order to keep the existing public API in tact, the library still has to manage cookies with `Plug.Conn` during the authentication process. This coupling has been moved one level higher so that it no longer touches `AuthenticationClient`.

### CODE REVIEW

**Comment by adamzaninovich** [comment]
I believe the only conflict stems from the fact that I moved a function from `Cookies` into `Auth`. Deleting that function from `Cookies`, as well as changing any references to point to `Auth` should fix it.

**Review by jsncmgs1 — COMMENTED** [review]
Looks good!  My only question would be is there value in having Spotify.Auth seperate from Spotify.Authentication?  Seems like it might be hard to make the distinction between what should do what.  Let me know your thoughts.

Besides that I can merge later tonight. Thanks!

**Comment by jsncmgs1** [comment]
Maybe we call it Spotify.Tokens, or something that makes the two distinguishable?

**Comment by adamzaninovich** [comment]
In my opinion, `Spotify.Auth` should definitely be separate from `Spotify.Authentication`. They each have a separate responsibility.

I thought about naming it `Spotify.Credentials` or `Spotify.Tokens` but it doesn't seem right to me to have a pluralized name. I think it's better to think of it as a single package that holds the auth data for Spotify. It's also much easier to use a struct when they have a short name, `%Plug.Conn{}` is a good example.

If it were me, I'd probably make an `OAuth` namespace and have

``` elixir
Spotify.OAuth.Authorization
Spotify.OAuth.Authentication
Spotify.OAuth.Authentication.Client
```

Then delegate the applicable functions in `Spotify`:

``` elixir
defmodule Spotify do
  @moduledoc false

  defdelegate authorization_url,          to: Spotify.OAuth.Authorization, as: :url
  defdelegate authenticate(conn, params), to: Spotify.OAuth.Authentication
  defdelegate refresh(conn),              to: Spotify.OAuth.Authentication

  #...
end
```

This way, the user doesn't have to worry about the distinction.

Having said all that, it's your library, and I'll happily make any changes you'd like.

**Comment by jsncmgs1** [comment]
In this case I think a pluralized name is preferable here to having `Auth` and `Authentication`, I agree that short names are easier, but I'd rather not have the confusion between 2 module names with the same meaning and one being a truncation of the other. Plus, we should all have tab-complete for those pesky long names anyway :).

An OAuth namespace was something I planned on doing earlier but never did for reasons which I forget, probably got distracted by another shiny new project somewhere. I like your delegation idea but I'm not asking you to do that. I think a name change here is fine, I personally like `Credentials` but don't have a strong opinion vs `Tokens`.

**Comment by adamzaninovich** [comment]
Sounds good. `Credentials` it is. I'll make the change asap.

**Comment by adamzaninovich** [comment]
Changes pushed! Let me know if I can do anything else. Thanks!

**Comment by jsncmgs1** [comment]
Merged as [37ccafe03b05bc99e8c6880e296c9fba10fb0bb6]. Apparently when you merge from the command line it doesn't recognize it 👎

**Comment by adamzaninovich** [comment]
Right on! Thanks man, I really appreciate the help! And thanks for all the hard work creating this library!

**Comment by steveklebanoff** [comment]
This is awesome - thanks gents!  Prior to this PR I was working around this in a janky way by doing something like this:

``` elixir
spotify_connection = %{cookies: %{
  "spotify_access_token" => Application.get_env(:my_app, :spotify_access_token)
}}
Spotify.Artist.get_top_tracks(spotify_connection, "solange", country: "US")
```

New approach is much better!

**Comment by morgz** [comment]
Thanks for working on this, just what I needed.

**Pull request closed without merging**
