### PR TITLE
Add library module

### LINKED ISSUE #29: Add support for Library API
I don't think any of the endpoints found in the [library API](https://developer.spotify.com/web-api/library-endpoints/) are found in other modules (i.e. not duplicated).

Would be great to have a module for this section. I'd be happy to implement & contribute this feature.

### PR DESCRIPTION
**Pull request by katbow**
Closes #29 

For the url versions, this contains a lot of duplication (e.g. `save_tracks_url/1` returns the same url as `get_saved_tracks_url/1` and `remove_saved_tracks_url/1`), however this seems to be the standard for the other modules.

Let me know if this is preferable, or to reduce the duplication by having a `saved_tracks_url/1` function which can be reused. It makes more sense to me to have a single url that is reused, since it's not specifically for getting/saving/deleting tracks until used in conjunction with the method.

Let me know what you think @jsncmgs1 !

### CODE REVIEW

**Comment by jsncmgs1** [comment]
I think it makes sense to reduce the duplication 👍 but im ok with this

**Review by jsncmgs1 — APPROVED** [review]

**Comment by katbow** [comment]
OK cool. I'll change that part for this PR.

**Comment by katbow** [comment]
All set now @jsncmgs1 👍

**Comment by jsncmgs1** [comment]
@katbow I changed the base branch to development, but am merging now.

**Pull request merged**
